# Generated by Django 6.0.3 on 2026-03-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('standard', '0003_rename_total_fees_standard_fees_alter_standard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='standard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='standard.standard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
