# Generated by Django 6.0.1 on 2026-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
