# Generated by Django 6.0.3 on 2026-03-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
