# Generated by Django 6.0.3 on 2026-03-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feespayment'),
        ('students', '0002_student_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeesPayment',
            new_name='FeePayment',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='paid_fees',
        ),
        migrations.AlterField(
            model_name='fees',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
