# Generated by Django 6.0.3 on 2026-03-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_rename_feespayment_feepayment_remove_fees_paid_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='discount',
        ),
    ]
