# Generated by Django 6.0.3 on 2026-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_fees_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fees',
            name='paid_fees',
            field=models.IntegerField(default=0),
        ),
    ]
