# Generated by Django 6.0.1 on 2026-03-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_fees', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
