# Generated by Django 6.0.1 on 2026-03-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='discount',
        ),
    ]
