# Generated by Django 6.0.3 on 2026-03-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_remove_standard_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='total_fees',
            new_name='fees',
        ),
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
