# Generated by Django 6.0.3 on 2026-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_rename_total_fees_standard_fees_alter_standard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='fees',
        ),
        migrations.AddField(
            model_name='standard',
            name='total_fees',
            field=models.IntegerField(default=0),
        ),
    ]
