# Generated by Django 6.0.3 on 2026-03-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_standard_exam_total_marks'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
